labs13-delphe/FrontendAuth

- package.json
- src/components/AskerDashboard.js
- src/components/QuestionForm.js
- src/components/Secret.js
- yarn.lock
AskerDashboard and QuestionForm files added to components
Team needs to figure out how to use Routes with Auth0
> AskerDashboard file

- src/App.js
- src/components/Secret.js
Added a case on App.js and a button on Secret.js to allow us to view example of Asker Dashboard for user 1 (pulling in data from backend)
> View AskerDashboard

- src/components/QuestionForm.js
* Question form works locally
* Will need to change local endpoints to heroku links
* When asker submits a question with a topic:
* a question is posted to the questions table and question's id is returned
* a topic is posted to and found within the topics table and that topic's id is returned
* both question_id and topic_id are sent in post request to question_topics table and a new record is added
> Question Form in AskerDashboard

- src/components/AskerDashboard/AskerAnswersList.js
- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerQuestionsList.js
- src/components/AskerDashboard/AskerSingleQuestion.js
-Breaking up huge chunk of code to smaller components
-Delete question functionality
-Changed local endpoints to heroku endpoints
> Added New Files to AskerDashboard folder

- public/index.html
- src/App.js
- src/components/AskerDashboard/AskerAnswersList.js
- src/components/AskerDashboard/AskerSingleQuestion.js
- src/components/AskerDashboard/QuestionUpdateForm.js
- Added QuestionUpdateForm to AskerDashboard folder
- QUF is routed through App.js
- updateQuestion function is on App.js (wasn't working properly on AskerDashboard) but invoked on QUF
> Update Question Functionality

- src/App.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/Community/Community.js
- src/components/Community/CommunityEachQuestion.js
- src/components/Community/CommunityQuestionsList.js
- Added community view for users to see questions from other users of the app
- Added route to UserProfile.js
-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [ ] My code has been reviewed by at …
> Community Questions

- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/AskerDashboard/QuestionUpdateForm.js
- src/components/AskerDashboard/x_AskerAnswersList.js
Fixing netlify warnings/bugs
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] Test A
-   [ ] Test B
-   [x] I have commented my code, particularly in …
> Fixing Netlify Warnings/Bugs

- src/components/Community/CommunityEachQuestion.js
- src/components/ExpertDashboard/ExpertDashboard.js
- src/components/ExpertDashboard/Question.js
- src/components/Users/SingleUser.js
- src/components/Users/UpdateProfile.js
- src/components/Users/UserProfile.js
- Fixed User Profile view to only render info for single user
- buttons to edit and delete if user_id matches that on localstorage
- otherwise, button to navigate back to previous page or message user (future)
- delete functionality completed
- edit functionality completed
-   [ ] …
> Fixed User Profile View

- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/AskerDashboard/AskerQuestionsList.js
- src/components/AskerDashboard/QuestionForm.js
- src/components/ExpertDashboard/ExpertDashboard.js
- src/components/ExpertDashboard/Question.js
- src/components/ExpertDashboard/QuestionsList.js
Added delete answer functionality on Expert Dashboard
-   [ ] Test A
-   [ ] Test B
-   [x] I have commented my …
> Delete Expert Answer Button

- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/Community/CommunityEachQuestion.js
- src/components/Community/CommunityQuestionsList.js
- src/components/ExpertDashboard/Question.js
- src/components/Users/SingleUser.js
- src/components/Users/UpdateProfile.js
Added asker's name, username, and link to profile on Expert Dashboard Questions
-   [ ] Test A
-   [ ] Test B
- …
> Adding Asker's name and link to profile on Expert Dashboard

- package.json
- src/App.js
- src/components/Secret.js
- src/components/UserFormTwo.js
- yarn.lock
Automatic routing based on user type and first time login. 
As a user, I would like to be able to create a unique profile my first time logging into the app.
As a user, I would like to be routed to the dashboard that corresponds to my user_type, so that I can ask questions in the appropriate location
As a user, I would like to be routed to the dashboard that corresponds to my user_type, so that I can answer questions in the appropriate location
> automatic routing to dashboards and form

- package.json
- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/AskerDashboard/QuestionForm.js
- src/components/Dashboard.js
- yarn.lock
- Incorporated and built on Josh's Material styles
- Edit and delete still work
- Added list of topics as buttons
- Added asker info to question card
-   [ ] Test A
-   [ ] Test B
-   [x] I have performed a self-review of …
> AskerDashboard Material UI

- src/App.js
- src/components/Community/Community.js
- src/components/Community/CommunityEachQuestion.js
- Styling the community thread view
-   [ ] Test A
-   [ ] Test B
-   [ ] My code has been reviewed by at least one peer
-   [x] I have commented my code, particularly …
> Community Thread Styling

- src/App.js
- src/components/Dashboard.js
- src/components/ExpertDashboard/ExpertDashboard.js
- src/components/ExpertDashboard/QuestionsList.js
- src/components/Secret.js
- src/components/Users/SingleUser.js
- src/components/Users/UserProfile.js
Created the generic outline for a user profile
-   [X] New feature (non-breaking change which adds functionality)
-   [X] Complete, but not tested (may need new tests)
-   [ ] Test A
-   [ ] Test B
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [ ] My code has been reviewed by at least one peer
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [X] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my …
> created outline in material-UI for user profile

- src/components/ExpertDashboard/ExpertDashboard.js
- src/components/ExpertDashboard/Question.js
- src/components/ExpertDashboard/QuestionsList.js
Incorporated Material UI styling into the functionality done by Lydia for the Expert Dashboard
-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [ ] My code has been reviewed by at …
> incorporated Material UI elements into Expert Dashboard

- src/components/ExpertDashboard/ExpertDashboard.js
- src/components/ExpertDashboard/Question.js
- src/components/ExpertDashboard/QuestionsList.js
- src/components/ExpertDashboard/TopicDropdown.js
Modified expert dashboard to render only the questions in the topic chosen by the expert
-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] My code has been reviewed by at least …
> Josh akeman branch

- src/App.css
- src/App.js
- src/components/Users/SingleUser.js
- src/components/Users/UserProfile.js
- src/components/landing/css/style.css
Description
styled user profile page. solver merge conflicts.
Type of change
Change Status
How Has This Been Tested?
Checklist
> user profile styled and responsive

- src/App.css
- src/components/Users/SingleUser.js
- src/components/landing/css/materialize.css
- src/components/landing/css/style.css
Description
fixed responsiveness issue on user profile - expert type text align left. and changed color of user name from teal to black per UX.
Type of change
Change Status
How Has This Been Tested?
Checklist
> fixed responsiveness issue on user Profile

- src/App.js
- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/AskerDashboard/AskerQuestionsList.js
- src/components/AskerDashboard/QuestionForm.js
- src/components/Community/Community.js
- src/components/Community/CommunityEachQuestion.js
- src/components/Community/CommunityQuestionsList.js
- src/components/NavBar.js
- Polishing AskerDashboard
- Polishing Community Page
- Polishing NavBar
-   [ ] Test A
-   [ ] Test B
-   [x] I …
> More Polishing AskerDashboard, Community, NavBar

- README.md
- package.json
- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerDashboard.spec.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/AskerDashboard/QuestionForm.spec.js
- src/components/Community/CommunityEachQuestion.js
- src/components/NavBar.js
- yarn.lock
- Basic unit tests for AskerDashboard.js
- Basic unit tests for QuestionForm.js
- Installed @testing-library/react as dev dependency
- Updating ReadMe documentation
-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [x] I have performed a …
> Tests for AskerDashboard

- src/components/Dashboard.js
- src/components/ExpertDashboard/ExpertDashboard.js
- src/components/ExpertDashboard/Question.js
- src/components/ExpertDashboard/QuestionsList.js
Post request to the answers table was reloading the actual DOM every time it was triggered. I moved the axios call and edited the route on the backend to return the answers with the new posted answer. Now it updates state automatically when triggered rendering just the individual component.
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] Complete, but not tested (may need new tests)
-   [ ] Test A
-   [ ] Test B
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [ ] My code has been reviewed by at least one peer
-   [X] I have …
> all of the operations on expert dashboard are updating state on the component. 

- public/index.html
- src/App.css
- src/components/Users/SingleUser.js
- src/components/Users/UpdateProfile.js
- src/components/landing/Landing.js
- src/components/landing/css/style.css
Saw some issues with landing page - put user profile form in it's own container.
Made user profile view responsive for iphoneX
Extended icon/features grey background across per kermitt/UX
Got rid of nav on landing page
Changed font to roboto per UX
Final polish on landing page mobile responsiveness
Fixed weird break on landing page responsiveness
Type of change
How Has This Been Tested?
Checklist
> put update profile form in it's own container style.css

- src/components/AskerDashboard/AskerDashboard.js
- src/components/AskerDashboard/AskerEachQuestion.js
- src/components/AskerDashboard/QuestionForm.js
- src/components/Community/Community.js
- src/components/Community/CommunityEachQuestion.js
- removed hover color on topic buttons
- fixed Community question card spacing on mobile view
- fixed Community title spacing on mobile view
-   [ ] Test A
-   [ ] Test B
-   [x] I have performed a self-review of my own …
> More Polishing

- src/components/ExpertDashboard/Question.js
also updated button styles to match the asker dashboard.
Fixed the issue of the answer count not updating depending on how many answers were currently displayed.
Updated buttons to match the styles on the asker dashboard.
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] Complete, but not tested (may need new tests)
-   [ ] Test A
-   [ ] Test B
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I …
> updates the answer count when you post or delete answers
